-- Sprint 16, Fase 4 (DEC-084): CAPE (Shiller P/E) do S&P 500, insumo de
-- valuation para VOO. Tabela global nova, mesmo padrao de acesso de
-- market_reference_rates (DEC-075): sem dono individual, sem RPC de
-- escrita para authenticated, so service_role via RPC dedicada - e nem
-- service_role escreve direto na tabela, so pela RPC.
--
-- Nao reaproveita market_reference_rates: essa exige `maturity_date not
-- null`, que nao faz sentido para CAPE (multiplo de valuation, nao taxa
-- de juros com prazo).

create table public.market_valuation_ratios (
  id bigint generated by default as identity primary key,
  series text not null,
  reference_date date not null,
  value_scaled bigint not null,
  value_scale integer not null default 1000000,
  source text not null,
  created_at timestamptz not null default now(),

  constraint market_valuation_ratios_series_check check (
    series in ('shiller-cape-sp500')
  ),
  constraint market_valuation_ratios_source_check check (
    source in ('shiller-yale')
  ),
  constraint market_valuation_ratios_value_scale_check check (
    value_scale = 1000000
  ),
  constraint market_valuation_ratios_value_scaled_check check (
    value_scaled > 0
  ),
  constraint market_valuation_ratios_identity_unique unique (
    series, source, reference_date
  )
);

create index market_valuation_ratios_series_reference_date_idx
on public.market_valuation_ratios (series, reference_date desc);

alter table public.market_valuation_ratios enable row level security;

create policy "Authenticated users can read global market valuation ratios"
on public.market_valuation_ratios
for select
to authenticated
using (true);

revoke all on table public.market_valuation_ratios from anon;
revoke all on table public.market_valuation_ratios from authenticated;
grant select on table public.market_valuation_ratios to authenticated;
grant select, insert, update, delete
on table public.market_valuation_ratios
to service_role;

revoke all on sequence public.market_valuation_ratios_id_seq from anon;
revoke all on sequence public.market_valuation_ratios_id_seq from authenticated;
grant usage, select
on sequence public.market_valuation_ratios_id_seq
to service_role;

create function public.upsert_market_valuation_ratios_v1(records jsonb)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_record_count integer;
  v_item jsonb;
  v_key_count integer;
  v_upserted_count integer;
begin
  if records is null or pg_catalog.jsonb_typeof(records) <> 'array' then
    raise exception using
      errcode = '22023',
      message = 'market valuation ratios batch must be an array';
  end if;

  v_record_count := pg_catalog.jsonb_array_length(records);
  if v_record_count > 20 then
    raise exception using
      errcode = '22023',
      message = 'market valuation ratios batch exceeds 20 records';
  end if;

  if v_record_count = 0 then
    return pg_catalog.jsonb_build_object('attempted', 0, 'upserted', 0);
  end if;

  for v_item in
    select value
    from pg_catalog.jsonb_array_elements(records)
  loop
    if pg_catalog.jsonb_typeof(v_item) <> 'object' then
      raise exception using
        errcode = '22023',
        message = 'market valuation ratio record must be an object';
    end if;

    if v_item ? 'id' or v_item ? 'created_at' then
      raise exception using
        errcode = '22023',
        message = 'market valuation ratio record must not set id or created_at';
    end if;

    select pg_catalog.count(*)
    into v_key_count
    from pg_catalog.jsonb_object_keys(v_item);

    if v_key_count <> 5
      or not (
        v_item ? 'series'
        and v_item ? 'reference_date'
        and v_item ? 'value_scaled'
        and v_item ? 'value_scale'
        and v_item ? 'source'
      )
    then
      raise exception using
        errcode = '22023',
        message = 'market valuation ratio record has invalid fields';
    end if;
  end loop;

  -- Stable contract-specific key: market_valuation_ratios.upsert.v1.
  perform pg_catalog.pg_advisory_xact_lock(5127493081662204471);

  insert into public.market_valuation_ratios (
    series,
    reference_date,
    value_scaled,
    value_scale,
    source
  )
  select
    populated.series,
    populated.reference_date,
    populated.value_scaled,
    populated.value_scale,
    populated.source
  from pg_catalog.jsonb_populate_recordset(
    null::public.market_valuation_ratios,
    records
  ) as populated
  on conflict (series, source, reference_date)
  do update set
    value_scaled = excluded.value_scaled,
    value_scale = excluded.value_scale;

  get diagnostics v_upserted_count = row_count;

  return pg_catalog.jsonb_build_object(
    'attempted', v_record_count,
    'upserted', v_upserted_count
  );
end;
$$;

comment on function public.upsert_market_valuation_ratios_v1(jsonb) is
'Atomically upserts global market valuation ratio batches for server-side callers, keyed by series + source + reference_date.';

revoke all on function public.upsert_market_valuation_ratios_v1(jsonb) from public;
revoke all on function public.upsert_market_valuation_ratios_v1(jsonb) from anon;
revoke all on function public.upsert_market_valuation_ratios_v1(jsonb) from authenticated;
grant execute on function public.upsert_market_valuation_ratios_v1(jsonb) to service_role;

revoke insert, update, delete, truncate
on table public.market_valuation_ratios
from service_role;
