create table public.fundamental_snapshots (
  id bigint generated by default as identity primary key,
  ticker text not null,
  category text not null,
  market text not null,
  kind text not null,
  period text not null,
  source text not null,
  reference_date date not null,
  source_document_id text not null,
  source_archive text not null,
  filing_version integer not null,
  exercise_order text not null,
  currency text not null,
  total_revenue_minor bigint,
  net_income_minor bigint,
  total_assets_minor bigint,
  total_equity_minor bigint,
  operating_cash_flow_minor bigint,
  provenance jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint fundamental_snapshots_ticker_check check (
    ticker = upper(trim(ticker))
    and length(ticker) > 0
  ),
  constraint fundamental_snapshots_identity_check check (
    category = 'brazilian-stock'
    and market = 'BR'
    and kind = 'brazilian-stock'
  ),
  constraint fundamental_snapshots_source_period_check check (
    (source = 'cvm-dfp' and period = 'annual')
    or (source = 'cvm-itr' and period = 'quarterly')
  ),
  constraint fundamental_snapshots_source_document_id_check check (
    length(trim(source_document_id)) > 0
  ),
  constraint fundamental_snapshots_source_archive_check check (
    length(trim(source_archive)) > 0
  ),
  constraint fundamental_snapshots_filing_version_check check (
    filing_version > 0
  ),
  constraint fundamental_snapshots_exercise_order_check check (
    length(trim(exercise_order)) > 0
  ),
  constraint fundamental_snapshots_currency_check check (currency = 'BRL'),
  constraint fundamental_snapshots_provenance_check check (
    jsonb_typeof(provenance) = 'object'
  ),
  constraint fundamental_snapshots_logical_identity_unique unique (
    ticker,
    category,
    market,
    kind,
    period,
    source,
    reference_date,
    source_document_id
  )
);

create trigger set_fundamental_snapshots_updated_at
before update on public.fundamental_snapshots
for each row
execute function public.set_updated_at();

alter table public.fundamental_snapshots enable row level security;

create policy "Authenticated users can read global fundamental snapshots"
on public.fundamental_snapshots
for select
to authenticated
using (true);

revoke all on table public.fundamental_snapshots from anon;
revoke all on table public.fundamental_snapshots from authenticated;
grant select on table public.fundamental_snapshots to authenticated;
grant select, insert, update, delete
on table public.fundamental_snapshots
to service_role;

revoke all on sequence public.fundamental_snapshots_id_seq from anon;
revoke all on sequence public.fundamental_snapshots_id_seq from authenticated;
grant usage, select
on sequence public.fundamental_snapshots_id_seq
to service_role;
