-- Sprint 16 pós-encerramento: histórico mensal de dividend yield de FII,
-- pra viabilizar o sinal de spread DY sobre NTN-B
-- (docs/reference/FII_SEGMENTOS_E_METRICAS.md, seção 3.2/7.2).
--
-- Fonte: coluna Percentual_Dividend_Yield_Mes do documento "complemento"
-- do Informe Mensal Estruturado da CVM (inf_mensal_fii_complemento_*.csv)
-- - mesmo arquivo já baixado e usado pelo pipeline de fundamental_snapshots
-- (patrimônio, cotas emitidas), campo nunca extraído até agora. Tabela
-- separada, não uma coluna nova em fundamental_snapshots: aquele pipeline
-- só guarda o mês mais recente por fundo (histórico é descartado na
-- extração), e o sinal precisa dos últimos 12 meses somados.
--
-- Chave (cnpj, reference_date, version), não (cnpj, reference_date): a
-- CVM permite reenvio de um mês com Versao incrementada (mesmo padrão de
-- "Protocolo Provento" em provento_declaration_values) - guarda todas as
-- versões, a agregação de leitura decide qual usar (versão mais alta por
-- mês vence), nunca resolvido na escrita.
--
-- Mesmo padrão de acesso de market_etf_valuations/provento_declaration_values:
-- tabela global, sem dono individual, sem RPC de escrita para
-- authenticated, só service_role via RPC dedicada.
create table public.fii_monthly_dividend_yield (
  id bigint generated by default as identity primary key,
  cnpj text not null,
  ticker text not null,
  reference_date date not null,
  version bigint not null,
  dividend_yield_unscaled bigint not null,
  dividend_yield_scale integer not null,
  source_archive text not null,
  extracted_at timestamptz not null default now(),

  constraint fii_monthly_dividend_yield_identity_unique unique (
    cnpj, reference_date, version
  ),
  constraint fii_monthly_dividend_yield_version_check check (
    version > 0
  ),
  constraint fii_monthly_dividend_yield_scale_check check (
    dividend_yield_scale >= 0 and dividend_yield_scale <= 32767
  )
);

create index fii_monthly_dividend_yield_cnpj_reference_date_idx
on public.fii_monthly_dividend_yield (cnpj, reference_date desc, version desc);

alter table public.fii_monthly_dividend_yield enable row level security;

create policy "Authenticated users can read global FII monthly dividend yield"
on public.fii_monthly_dividend_yield
for select
to authenticated
using (true);

revoke all on table public.fii_monthly_dividend_yield from anon;
revoke all on table public.fii_monthly_dividend_yield from authenticated;
grant select on table public.fii_monthly_dividend_yield to authenticated;
grant select, insert, update, delete
on table public.fii_monthly_dividend_yield
to service_role;

revoke all on sequence public.fii_monthly_dividend_yield_id_seq from anon;
revoke all on sequence public.fii_monthly_dividend_yield_id_seq from authenticated;
grant usage, select
on sequence public.fii_monthly_dividend_yield_id_seq
to service_role;

create function public.upsert_fii_monthly_dividend_yield_v1(records jsonb)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_record_count integer;
  v_item jsonb;
  v_key_count integer;
  v_upserted_count integer;
begin
  if records is null or pg_catalog.jsonb_typeof(records) <> 'array' then
    raise exception using
      errcode = '22023',
      message = 'FII monthly dividend yield batch must be an array';
  end if;

  v_record_count := pg_catalog.jsonb_array_length(records);
  if v_record_count > 100 then
    raise exception using
      errcode = '22023',
      message = 'FII monthly dividend yield batch exceeds 100 records';
  end if;

  if v_record_count = 0 then
    return pg_catalog.jsonb_build_object('attempted', 0, 'upserted', 0);
  end if;

  for v_item in
    select value
    from pg_catalog.jsonb_array_elements(records)
  loop
    if pg_catalog.jsonb_typeof(v_item) <> 'object' then
      raise exception using
        errcode = '22023',
        message = 'FII monthly dividend yield record must be an object';
    end if;

    if v_item ? 'id' or v_item ? 'extracted_at' then
      raise exception using
        errcode = '22023',
        message = 'FII monthly dividend yield record must not set id or extracted_at';
    end if;

    select pg_catalog.count(*)
    into v_key_count
    from pg_catalog.jsonb_object_keys(v_item);

    if v_key_count <> 7
      or not (
        v_item ? 'cnpj'
        and v_item ? 'ticker'
        and v_item ? 'reference_date'
        and v_item ? 'version'
        and v_item ? 'dividend_yield_unscaled'
        and v_item ? 'dividend_yield_scale'
        and v_item ? 'source_archive'
      )
    then
      raise exception using
        errcode = '22023',
        message = 'FII monthly dividend yield record has invalid fields';
    end if;
  end loop;

  -- Stable contract-specific key: fii_monthly_dividend_yield.upsert.v1.
  perform pg_catalog.pg_advisory_xact_lock(2847196350471928361);

  insert into public.fii_monthly_dividend_yield (
    cnpj,
    ticker,
    reference_date,
    version,
    dividend_yield_unscaled,
    dividend_yield_scale,
    source_archive
  )
  select
    populated.cnpj,
    populated.ticker,
    populated.reference_date,
    populated.version,
    populated.dividend_yield_unscaled,
    populated.dividend_yield_scale,
    populated.source_archive
  from pg_catalog.jsonb_populate_recordset(
    null::public.fii_monthly_dividend_yield,
    records
  ) as populated
  on conflict (cnpj, reference_date, version)
  do update set
    ticker = excluded.ticker,
    dividend_yield_unscaled = excluded.dividend_yield_unscaled,
    dividend_yield_scale = excluded.dividend_yield_scale,
    source_archive = excluded.source_archive;

  get diagnostics v_upserted_count = row_count;

  return pg_catalog.jsonb_build_object(
    'attempted', v_record_count,
    'upserted', v_upserted_count
  );
end;
$$;

comment on function public.upsert_fii_monthly_dividend_yield_v1(jsonb) is
'Atomically upserts global FII monthly dividend yield batches (CVM Informe Mensal complemento) for server-side callers, keyed by cnpj + reference_date + version.';

revoke all on function public.upsert_fii_monthly_dividend_yield_v1(jsonb) from public;
revoke all on function public.upsert_fii_monthly_dividend_yield_v1(jsonb) from anon;
revoke all on function public.upsert_fii_monthly_dividend_yield_v1(jsonb) from authenticated;
grant execute on function public.upsert_fii_monthly_dividend_yield_v1(jsonb) to service_role;

revoke insert, update, delete, truncate
on table public.fii_monthly_dividend_yield
from service_role;
