-- Sprint 16, Fase 4 fatia ETF (DEC-092): prêmio/desconto de ETF sobre o NAV.
-- Tabela global nova, mesmo padrão de acesso de market_reference_rates
-- (DEC-075) e market_valuation_ratios (DEC-084): sem dono individual, sem
-- RPC de escrita para authenticated, só service_role via RPC dedicada.
--
-- Não reaproveita market_valuation_ratios: aquela exige
-- `value_scaled > 0` (adequado pro CAPE, que nunca é negativo) e
-- `source in ('shiller-yale')`. Prêmio/desconto é signed (pode ser
-- desconto, valor negativo) e a fonte é o site do próprio emissor
-- (`vanguard-site`), não um filing regulatório nem um dataset acadêmico -
-- semântica e invariantes diferentes o bastante pra não forçar na mesma
-- tabela.
--
-- Identidade por ativo via coluna `ticker` (diferente de
-- market_valuation_ratios, que não precisa de identidade de ativo porque
-- CAPE é agregado de índice, não por ETF).

create table public.market_etf_valuations (
  id bigint generated by default as identity primary key,
  ticker text not null,
  reference_date date not null,
  premium_discount_basis_points bigint not null,
  source text not null,
  created_at timestamptz not null default now(),

  constraint market_etf_valuations_ticker_check check (
    ticker in ('VOO', 'VNQ', 'VEA')
  ),
  constraint market_etf_valuations_source_check check (
    source in ('vanguard-site')
  ),
  constraint market_etf_valuations_identity_unique unique (
    ticker, source, reference_date
  )
);

create index market_etf_valuations_ticker_reference_date_idx
on public.market_etf_valuations (ticker, reference_date desc);

alter table public.market_etf_valuations enable row level security;

create policy "Authenticated users can read global ETF valuations"
on public.market_etf_valuations
for select
to authenticated
using (true);

revoke all on table public.market_etf_valuations from anon;
revoke all on table public.market_etf_valuations from authenticated;
grant select on table public.market_etf_valuations to authenticated;
grant select, insert, update, delete
on table public.market_etf_valuations
to service_role;

revoke all on sequence public.market_etf_valuations_id_seq from anon;
revoke all on sequence public.market_etf_valuations_id_seq from authenticated;
grant usage, select
on sequence public.market_etf_valuations_id_seq
to service_role;

create function public.upsert_market_etf_valuations_v1(records jsonb)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_record_count integer;
  v_item jsonb;
  v_key_count integer;
  v_upserted_count integer;
begin
  if records is null or pg_catalog.jsonb_typeof(records) <> 'array' then
    raise exception using
      errcode = '22023',
      message = 'ETF valuations batch must be an array';
  end if;

  v_record_count := pg_catalog.jsonb_array_length(records);
  if v_record_count > 20 then
    raise exception using
      errcode = '22023',
      message = 'ETF valuations batch exceeds 20 records';
  end if;

  if v_record_count = 0 then
    return pg_catalog.jsonb_build_object('attempted', 0, 'upserted', 0);
  end if;

  for v_item in
    select value
    from pg_catalog.jsonb_array_elements(records)
  loop
    if pg_catalog.jsonb_typeof(v_item) <> 'object' then
      raise exception using
        errcode = '22023',
        message = 'ETF valuation record must be an object';
    end if;

    if v_item ? 'id' or v_item ? 'created_at' then
      raise exception using
        errcode = '22023',
        message = 'ETF valuation record must not set id or created_at';
    end if;

    select pg_catalog.count(*)
    into v_key_count
    from pg_catalog.jsonb_object_keys(v_item);

    if v_key_count <> 4
      or not (
        v_item ? 'ticker'
        and v_item ? 'reference_date'
        and v_item ? 'premium_discount_basis_points'
        and v_item ? 'source'
      )
    then
      raise exception using
        errcode = '22023',
        message = 'ETF valuation record has invalid fields';
    end if;
  end loop;

  -- Stable contract-specific key: market_etf_valuations.upsert.v1.
  perform pg_catalog.pg_advisory_xact_lock(2977164835012933941);

  insert into public.market_etf_valuations (
    ticker,
    reference_date,
    premium_discount_basis_points,
    source
  )
  select
    populated.ticker,
    populated.reference_date,
    populated.premium_discount_basis_points,
    populated.source
  from pg_catalog.jsonb_populate_recordset(
    null::public.market_etf_valuations,
    records
  ) as populated
  on conflict (ticker, source, reference_date)
  do update set
    premium_discount_basis_points = excluded.premium_discount_basis_points;

  get diagnostics v_upserted_count = row_count;

  return pg_catalog.jsonb_build_object(
    'attempted', v_record_count,
    'upserted', v_upserted_count
  );
end;
$$;

comment on function public.upsert_market_etf_valuations_v1(jsonb) is
'Atomically upserts global ETF valuation batches (premium/discount vs NAV) for server-side callers, keyed by ticker + source + reference_date.';

revoke all on function public.upsert_market_etf_valuations_v1(jsonb) from public;
revoke all on function public.upsert_market_etf_valuations_v1(jsonb) from anon;
revoke all on function public.upsert_market_etf_valuations_v1(jsonb) from authenticated;
grant execute on function public.upsert_market_etf_valuations_v1(jsonb) to service_role;

revoke insert, update, delete, truncate
on table public.market_etf_valuations
from service_role;
