-- Tabela global de cotacoes de mercado (Sprint 5, DEC-052).
--
-- asset_prices (20260710174244_create_asset_prices.sql) e por usuario: cada
-- usuario autenticado que dispara refresh-market-data grava sua propria copia
-- das mesmas cotacoes publicas, porque a Edge Function roda sob o JWT do
-- usuario. Isso impede agendamento via pg_cron (nao existe usuario num job
-- agendado) e duplica o mesmo dado publico por usuario. market_asset_prices
-- e' uma tabela nova e independente - a antiga asset_prices permanece
-- intocada e em uso ate um ciclo futuro confirmar que nada mais depende dela.
--
-- Mesmo padrao ja usado por fundamental_snapshots e official_asset_events:
-- sem user_id, identidade por ticker (nao FK para assets, que e' por
-- usuario), leitura authenticated via RLS, escrita exclusiva de service_role
-- via RPC transacional.

create table public.market_asset_prices (
  id bigint generated by default as identity primary key,
  ticker text not null,
  market text not null,
  currency text not null,
  price_minor bigint not null,
  priced_at timestamptz not null,
  source text not null,
  created_at timestamptz not null default now(),

  constraint market_asset_prices_ticker_check check (
    ticker = upper(trim(ticker))
    and length(ticker) > 0
  ),
  constraint market_asset_prices_market_check check (
    market in ('BR', 'US')
  ),
  constraint market_asset_prices_currency_check check (
    currency in ('BRL', 'USD')
  ),
  constraint market_asset_prices_price_minor_positive check (
    price_minor > 0
  ),
  constraint market_asset_prices_source_check check (
    source = 'market-provider'
  ),
  constraint market_asset_prices_identity_unique unique (
    ticker,
    source,
    priced_at
  )
);

create index market_asset_prices_ticker_priced_at_idx
on public.market_asset_prices (ticker, priced_at desc);

alter table public.market_asset_prices enable row level security;

create policy "Authenticated users can read global market asset prices"
on public.market_asset_prices
for select
to authenticated
using (true);

revoke all on table public.market_asset_prices from anon;
revoke all on table public.market_asset_prices from authenticated;
grant select on table public.market_asset_prices to authenticated;
grant select, insert, update, delete
on table public.market_asset_prices
to service_role;

revoke all on sequence public.market_asset_prices_id_seq from anon;
revoke all on sequence public.market_asset_prices_id_seq from authenticated;
grant usage, select
on sequence public.market_asset_prices_id_seq
to service_role;

-- RPC transacional de upsert, mesmo padrao de upsert_fundamental_snapshots_v1
-- (docs/PROJECT_HANDOFF.md secao 8): toda variavel PL/pgSQL usa prefixo v_
-- para nunca colidir com nome de coluna real da tabela, e COALESCE nunca e'
-- qualificado por schema.

create function public.upsert_market_asset_prices_v1(records jsonb)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_record_count integer;
  v_item jsonb;
  v_key_count integer;
  v_upserted_count integer;
begin
  if records is null or pg_catalog.jsonb_typeof(records) <> 'array' then
    raise exception using
      errcode = '22023',
      message = 'market asset prices batch must be an array';
  end if;

  v_record_count := pg_catalog.jsonb_array_length(records);
  if v_record_count > 100 then
    raise exception using
      errcode = '22023',
      message = 'market asset prices batch exceeds 100 records';
  end if;

  if v_record_count = 0 then
    return pg_catalog.jsonb_build_object('attempted', 0, 'upserted', 0);
  end if;

  for v_item in
    select value
    from pg_catalog.jsonb_array_elements(records)
  loop
    if pg_catalog.jsonb_typeof(v_item) <> 'object' then
      raise exception using
        errcode = '22023',
        message = 'market asset price record must be an object';
    end if;

    if v_item ? 'id' or v_item ? 'created_at' then
      raise exception using
        errcode = '22023',
        message = 'market asset price record must not set id or created_at';
    end if;

    select pg_catalog.count(*)
    into v_key_count
    from pg_catalog.jsonb_object_keys(v_item);

    if v_key_count <> 6
      or not (
        v_item ? 'ticker'
        and v_item ? 'market'
        and v_item ? 'currency'
        and v_item ? 'price_minor'
        and v_item ? 'priced_at'
        and v_item ? 'source'
      )
    then
      raise exception using
        errcode = '22023',
        message = 'market asset price record has invalid fields';
    end if;
  end loop;

  -- Stable contract-specific key: market_asset_prices.upsert.v1.
  perform pg_catalog.pg_advisory_xact_lock(4826317092550671821);

  insert into public.market_asset_prices (
    ticker,
    market,
    currency,
    price_minor,
    priced_at,
    source
  )
  select
    populated.ticker,
    populated.market,
    populated.currency,
    populated.price_minor,
    populated.priced_at,
    populated.source
  from pg_catalog.jsonb_populate_recordset(
    null::public.market_asset_prices,
    records
  ) as populated
  on conflict (ticker, source, priced_at)
  do update set
    market = excluded.market,
    currency = excluded.currency,
    price_minor = excluded.price_minor;

  get diagnostics v_upserted_count = row_count;

  return pg_catalog.jsonb_build_object(
    'attempted', v_record_count,
    'upserted', v_upserted_count
  );
end;
$$;

comment on function public.upsert_market_asset_prices_v1(jsonb) is
'Atomically upserts global market asset price batches for server-side callers, keyed by ticker + source + priced_at.';

revoke all on function public.upsert_market_asset_prices_v1(jsonb) from public;
revoke all on function public.upsert_market_asset_prices_v1(jsonb) from anon;
revoke all on function public.upsert_market_asset_prices_v1(jsonb) from authenticated;
grant execute on function public.upsert_market_asset_prices_v1(jsonb) to service_role;

revoke insert, update, delete, truncate
on table public.market_asset_prices
from service_role;
