-- Sprint 16 pós-encerramento (DEC-097/DEC-101): valor extraído do
-- formulário "Provento" estruturado da CVM, por ISIN, para cada
-- official_asset_event de categoria dividend-or-distribution.
--
-- Mesmo padrão de acesso de market_etf_valuations (DEC-092): tabela
-- global, sem dono individual, sem RPC de escrita para authenticated, só
-- service_role via RPC dedicada.
--
-- Valor bruto por ação armazenado como decimal exato (unscaled + scale,
-- mesmo padrão de issued_shares_unscaled/issued_shares_scale em
-- fundamental_snapshots), não como FUNDAMENTAL_RATIO_SCALE (1e6): o
-- formulário da CVM chega com até 11 casas decimais
-- (ex.: 0,48320810620) e o projeto nunca trunca precisão de fonte sem
-- necessidade.
--
-- protocol/version são o "Protocolo Provento" interno do documento
-- (DEC-101, não confundir com numProtocolo/numSequencia/numVersao do
-- ENET, já embutidos na identidade do official_asset_event) - permitem
-- dedup real: duas submissões ENET diferentes podem compartilhar o
-- mesmo Protocolo Provento com Versão incrementada quando a empresa
-- reenvia uma correção da mesma declaração. Identidade de armazenamento
-- é (event_id, isin) porque cada official_asset_event é um documento
-- só; a agregação por protocolo (pegar a versão mais alta) acontece na
-- leitura, não na escrita.
create table public.provento_declaration_values (
  id bigint generated by default as identity primary key,
  event_id text not null references public.official_asset_events (event_id),
  isin text not null,
  protocol text not null,
  version bigint not null,
  gross_value_per_share_unscaled bigint not null,
  gross_value_per_share_scale integer not null,
  period_base text not null,
  fiscal_year integer not null,
  payment_date date not null,
  sent_at date not null,
  parser_version text not null,
  extracted_at timestamptz not null default now(),

  constraint provento_declaration_values_event_isin_unique unique (
    event_id, isin
  ),
  constraint provento_declaration_values_version_check check (
    version > 0
  ),
  constraint provento_declaration_values_unscaled_check check (
    gross_value_per_share_unscaled >= 0
  ),
  constraint provento_declaration_values_scale_check check (
    gross_value_per_share_scale >= 0 and gross_value_per_share_scale <= 32767
  ),
  constraint provento_declaration_values_fiscal_year_check check (
    fiscal_year >= 2003 and fiscal_year <= 9999
  )
);

create index provento_declaration_values_protocol_version_idx
on public.provento_declaration_values (protocol, version desc);

create index provento_declaration_values_isin_payment_date_idx
on public.provento_declaration_values (isin, payment_date desc);

alter table public.provento_declaration_values enable row level security;

create policy "Authenticated users can read global provento declaration values"
on public.provento_declaration_values
for select
to authenticated
using (true);

revoke all on table public.provento_declaration_values from anon;
revoke all on table public.provento_declaration_values from authenticated;
grant select on table public.provento_declaration_values to authenticated;
grant select, insert, update, delete
on table public.provento_declaration_values
to service_role;

revoke all on sequence public.provento_declaration_values_id_seq from anon;
revoke all on sequence public.provento_declaration_values_id_seq from authenticated;
grant usage, select
on sequence public.provento_declaration_values_id_seq
to service_role;

create function public.upsert_provento_declaration_values_v1(records jsonb)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_record_count integer;
  v_item jsonb;
  v_key_count integer;
  v_upserted_count integer;
begin
  if records is null or pg_catalog.jsonb_typeof(records) <> 'array' then
    raise exception using
      errcode = '22023',
      message = 'Provento declaration values batch must be an array';
  end if;

  v_record_count := pg_catalog.jsonb_array_length(records);
  if v_record_count > 100 then
    raise exception using
      errcode = '22023',
      message = 'Provento declaration values batch exceeds 100 records';
  end if;

  if v_record_count = 0 then
    return pg_catalog.jsonb_build_object('attempted', 0, 'upserted', 0);
  end if;

  for v_item in
    select value
    from pg_catalog.jsonb_array_elements(records)
  loop
    if pg_catalog.jsonb_typeof(v_item) <> 'object' then
      raise exception using
        errcode = '22023',
        message = 'Provento declaration value record must be an object';
    end if;

    if v_item ? 'id' or v_item ? 'extracted_at' then
      raise exception using
        errcode = '22023',
        message = 'Provento declaration value record must not set id or extracted_at';
    end if;

    select pg_catalog.count(*)
    into v_key_count
    from pg_catalog.jsonb_object_keys(v_item);

    if v_key_count <> 11
      or not (
        v_item ? 'event_id'
        and v_item ? 'isin'
        and v_item ? 'protocol'
        and v_item ? 'version'
        and v_item ? 'gross_value_per_share_unscaled'
        and v_item ? 'gross_value_per_share_scale'
        and v_item ? 'period_base'
        and v_item ? 'fiscal_year'
        and v_item ? 'payment_date'
        and v_item ? 'sent_at'
        and v_item ? 'parser_version'
      )
    then
      raise exception using
        errcode = '22023',
        message = 'Provento declaration value record has invalid fields';
    end if;
  end loop;

  -- Stable contract-specific key: provento_declaration_values.upsert.v1.
  perform pg_catalog.pg_advisory_xact_lock(4108552963371294187);

  insert into public.provento_declaration_values (
    event_id,
    isin,
    protocol,
    version,
    gross_value_per_share_unscaled,
    gross_value_per_share_scale,
    period_base,
    fiscal_year,
    payment_date,
    sent_at,
    parser_version
  )
  select
    populated.event_id,
    populated.isin,
    populated.protocol,
    populated.version,
    populated.gross_value_per_share_unscaled,
    populated.gross_value_per_share_scale,
    populated.period_base,
    populated.fiscal_year,
    populated.payment_date,
    populated.sent_at,
    populated.parser_version
  from pg_catalog.jsonb_populate_recordset(
    null::public.provento_declaration_values,
    records
  ) as populated
  on conflict (event_id, isin)
  do update set
    protocol = excluded.protocol,
    version = excluded.version,
    gross_value_per_share_unscaled = excluded.gross_value_per_share_unscaled,
    gross_value_per_share_scale = excluded.gross_value_per_share_scale,
    period_base = excluded.period_base,
    fiscal_year = excluded.fiscal_year,
    payment_date = excluded.payment_date,
    sent_at = excluded.sent_at,
    parser_version = excluded.parser_version;

  get diagnostics v_upserted_count = row_count;

  return pg_catalog.jsonb_build_object(
    'attempted', v_record_count,
    'upserted', v_upserted_count
  );
end;
$$;

comment on function public.upsert_provento_declaration_values_v1(jsonb) is
'Atomically upserts global provento declaration value batches (gross value per share extracted from CVM Provento forms) for server-side callers, keyed by event_id + isin.';

revoke all on function public.upsert_provento_declaration_values_v1(jsonb) from public;
revoke all on function public.upsert_provento_declaration_values_v1(jsonb) from anon;
revoke all on function public.upsert_provento_declaration_values_v1(jsonb) from authenticated;
grant execute on function public.upsert_provento_declaration_values_v1(jsonb) to service_role;

revoke insert, update, delete, truncate
on table public.provento_declaration_values
from service_role;
