-- Tabela global de taxas de cambio (Sprint 5, DEC-052). Mesma motivacao de
-- market_asset_prices na migration anterior: exchange_rates
-- (20260713162000_create_exchange_rates.sql) e por usuario e nao pode ser
-- alimentada por um job agendado sem usuario. A tabela antiga permanece
-- intocada e em uso ate um ciclo futuro confirmar que nada mais depende dela.
--
-- Diferenca de produto explicita (DEC-052): a edicao manual de cambio
-- (saveManualUsdBrl, hoje exposta nas telas Dashboard/Carteira/Estrategia/
-- Aporte) e' removida junto desta migracao. Cambio global nao tem dono
-- individual para sobrescrever; o valor automatico via refresh-market-data ja
-- roda de verdade (DEC-043). Nenhuma RPC de escrita para authenticated existe
-- aqui de proposito.

create table public.market_exchange_rates (
  id bigint generated by default as identity primary key,
  base_currency text not null,
  quote_currency text not null,
  rate_scaled bigint not null,
  rate_scale integer not null default 1000000,
  priced_at timestamptz not null,
  source text not null,
  created_at timestamptz not null default now(),

  constraint market_exchange_rates_base_currency_check check (
    base_currency in ('BRL', 'USD')
  ),
  constraint market_exchange_rates_quote_currency_check check (
    quote_currency in ('BRL', 'USD')
  ),
  constraint market_exchange_rates_distinct_currency_check check (
    base_currency <> quote_currency
  ),
  constraint market_exchange_rates_rate_scaled_positive check (
    rate_scaled > 0
  ),
  constraint market_exchange_rates_rate_scale_check check (
    rate_scale = 1000000
  ),
  constraint market_exchange_rates_source_check check (
    source = 'market-provider'
  ),
  constraint market_exchange_rates_identity_unique unique (
    base_currency,
    quote_currency,
    source,
    priced_at
  )
);

create index market_exchange_rates_pair_priced_at_idx
on public.market_exchange_rates (base_currency, quote_currency, priced_at desc);

alter table public.market_exchange_rates enable row level security;

create policy "Authenticated users can read global market exchange rates"
on public.market_exchange_rates
for select
to authenticated
using (true);

revoke all on table public.market_exchange_rates from anon;
revoke all on table public.market_exchange_rates from authenticated;
grant select on table public.market_exchange_rates to authenticated;
grant select, insert, update, delete
on table public.market_exchange_rates
to service_role;

revoke all on sequence public.market_exchange_rates_id_seq from anon;
revoke all on sequence public.market_exchange_rates_id_seq from authenticated;
grant usage, select
on sequence public.market_exchange_rates_id_seq
to service_role;

create function public.upsert_market_exchange_rates_v1(records jsonb)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_record_count integer;
  v_item jsonb;
  v_key_count integer;
  v_upserted_count integer;
begin
  if records is null or pg_catalog.jsonb_typeof(records) <> 'array' then
    raise exception using
      errcode = '22023',
      message = 'market exchange rates batch must be an array';
  end if;

  v_record_count := pg_catalog.jsonb_array_length(records);
  if v_record_count > 100 then
    raise exception using
      errcode = '22023',
      message = 'market exchange rates batch exceeds 100 records';
  end if;

  if v_record_count = 0 then
    return pg_catalog.jsonb_build_object('attempted', 0, 'upserted', 0);
  end if;

  for v_item in
    select value
    from pg_catalog.jsonb_array_elements(records)
  loop
    if pg_catalog.jsonb_typeof(v_item) <> 'object' then
      raise exception using
        errcode = '22023',
        message = 'market exchange rate record must be an object';
    end if;

    if v_item ? 'id' or v_item ? 'created_at' then
      raise exception using
        errcode = '22023',
        message = 'market exchange rate record must not set id or created_at';
    end if;

    select pg_catalog.count(*)
    into v_key_count
    from pg_catalog.jsonb_object_keys(v_item);

    if v_key_count <> 6
      or not (
        v_item ? 'base_currency'
        and v_item ? 'quote_currency'
        and v_item ? 'rate_scaled'
        and v_item ? 'rate_scale'
        and v_item ? 'priced_at'
        and v_item ? 'source'
      )
    then
      raise exception using
        errcode = '22023',
        message = 'market exchange rate record has invalid fields';
    end if;
  end loop;

  -- Stable contract-specific key: market_exchange_rates.upsert.v1.
  perform pg_catalog.pg_advisory_xact_lock(4826317092550671822);

  insert into public.market_exchange_rates (
    base_currency,
    quote_currency,
    rate_scaled,
    rate_scale,
    priced_at,
    source
  )
  select
    populated.base_currency,
    populated.quote_currency,
    populated.rate_scaled,
    populated.rate_scale,
    populated.priced_at,
    populated.source
  from pg_catalog.jsonb_populate_recordset(
    null::public.market_exchange_rates,
    records
  ) as populated
  on conflict (base_currency, quote_currency, source, priced_at)
  do update set
    rate_scaled = excluded.rate_scaled,
    rate_scale = excluded.rate_scale;

  get diagnostics v_upserted_count = row_count;

  return pg_catalog.jsonb_build_object(
    'attempted', v_record_count,
    'upserted', v_upserted_count
  );
end;
$$;

comment on function public.upsert_market_exchange_rates_v1(jsonb) is
'Atomically upserts global market exchange rate batches for server-side callers, keyed by currency pair + source + priced_at.';

revoke all on function public.upsert_market_exchange_rates_v1(jsonb) from public;
revoke all on function public.upsert_market_exchange_rates_v1(jsonb) from anon;
revoke all on function public.upsert_market_exchange_rates_v1(jsonb) from authenticated;
grant execute on function public.upsert_market_exchange_rates_v1(jsonb) to service_role;

revoke insert, update, delete, truncate
on table public.market_exchange_rates
from service_role;
