-- Sprint 16 pós-encerramento: valor de distribuição por cota dos ETFs
-- internacionais, pra viabilizar o sinal de spread de DY sobre a TIPS de
-- 10 anos (docs/reference/REGRAS_DE_PONTUACAO_RASCUNHO.md, seção 4).
--
-- Fonte: tabela "Financial Highlights" da classe ETF de cada fundo, no
-- N-CSR anual (relatório anual auditado) protocolado na SEC. Linhas
-- "Total Distributions" e "Net Asset Value, End of Period" do exercício.
-- Confirmado com filing real de VNQ (Vanguard Specialized Funds, CIK
-- 0000734383, accession 0001104659-26-036013, exercício encerrado em
-- 31/01/2026) e também para VOO e VEA.
--
-- Granularidade ANUAL: ao contrário do provento de ação e do informe
-- mensal de FII, aqui não existe agregação trailing-12-meses a fazer -
-- o próprio documento já publica o total do exercício. Por isso a chave
-- é (ticker, fiscal_year_end_date), sem versão: um exercício, um número.
-- Reprotocolo (N-CSR/A) sobrescreve pela mesma chave, com o
-- accession_number novo registrado.
--
-- Sem FK para official_asset_events (diferente de
-- provento_declaration_values): o pipeline de eventos oficiais da SEC
-- EDGAR nunca rodou em produção - `official_asset_events` tem 1.511
-- linhas, todas de CVM (5 ações + 4 FIIs), zero para VOO/VNQ/VEA
-- (verificado por SQL somente leitura em 07/08/2026). Amarrar o valor a
-- um evento inexistente bloquearia o sinal por uma dependência que não
-- é dele; a identidade documental (CIK + accession + URL) fica na
-- própria linha e continua auditável.
--
-- Mesmo padrão de acesso de market_etf_valuations (DEC-092),
-- provento_declaration_values (DEC-102) e fii_monthly_dividend_yield:
-- tabela global, sem dono individual, RLS com leitura para
-- `authenticated` e escrita só por `service_role` via RPC dedicada.
create table public.etf_distribution_values (
  id bigint generated by default as identity primary key,
  ticker text not null,
  registrant_cik text not null,
  accession_number text not null,
  fund_name text not null,
  share_class_label text not null,
  fiscal_year_end_date date not null,
  total_distributions_per_share_unscaled bigint not null,
  total_distributions_per_share_scale integer not null,
  net_asset_value_end_of_period_unscaled bigint not null,
  net_asset_value_end_of_period_scale integer not null,
  source_document_url text not null,
  extracted_at timestamptz not null default now(),

  constraint etf_distribution_values_ticker_check check (
    ticker in ('VOO', 'VNQ', 'VEA')
  ),
  constraint etf_distribution_values_identity_unique unique (
    ticker, fiscal_year_end_date
  ),
  constraint etf_distribution_values_distributions_check check (
    total_distributions_per_share_unscaled >= 0
    and total_distributions_per_share_scale >= 0
    and total_distributions_per_share_scale <= 32767
  ),
  constraint etf_distribution_values_nav_check check (
    net_asset_value_end_of_period_unscaled > 0
    and net_asset_value_end_of_period_scale >= 0
    and net_asset_value_end_of_period_scale <= 32767
  ),
  constraint etf_distribution_values_source_url_check check (
    source_document_url like 'https://www.sec.gov/Archives/edgar/%'
  )
);

create index etf_distribution_values_ticker_fiscal_year_idx
on public.etf_distribution_values (ticker, fiscal_year_end_date desc);

alter table public.etf_distribution_values enable row level security;

create policy "Authenticated users can read global ETF distribution values"
on public.etf_distribution_values
for select
to authenticated
using (true);

revoke all on table public.etf_distribution_values from anon;
revoke all on table public.etf_distribution_values from authenticated;
grant select on table public.etf_distribution_values to authenticated;
grant select, insert, update, delete
on table public.etf_distribution_values
to service_role;

revoke all on sequence public.etf_distribution_values_id_seq from anon;
revoke all on sequence public.etf_distribution_values_id_seq from authenticated;
grant usage, select
on sequence public.etf_distribution_values_id_seq
to service_role;

create function public.upsert_etf_distribution_values_v1(records jsonb)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_record_count integer;
  v_item jsonb;
  v_key_count integer;
  v_upserted_count integer;
begin
  if records is null or pg_catalog.jsonb_typeof(records) <> 'array' then
    raise exception using
      errcode = '22023',
      message = 'ETF distribution values batch must be an array';
  end if;

  v_record_count := pg_catalog.jsonb_array_length(records);
  if v_record_count > 20 then
    raise exception using
      errcode = '22023',
      message = 'ETF distribution values batch exceeds 20 records';
  end if;

  if v_record_count = 0 then
    return pg_catalog.jsonb_build_object('attempted', 0, 'upserted', 0);
  end if;

  for v_item in
    select value
    from pg_catalog.jsonb_array_elements(records)
  loop
    if pg_catalog.jsonb_typeof(v_item) <> 'object' then
      raise exception using
        errcode = '22023',
        message = 'ETF distribution value record must be an object';
    end if;

    if v_item ? 'id' or v_item ? 'extracted_at' then
      raise exception using
        errcode = '22023',
        message = 'ETF distribution value record must not set id or extracted_at';
    end if;

    select pg_catalog.count(*)
    into v_key_count
    from pg_catalog.jsonb_object_keys(v_item);

    if v_key_count <> 11
      or not (
        v_item ? 'ticker'
        and v_item ? 'registrant_cik'
        and v_item ? 'accession_number'
        and v_item ? 'fund_name'
        and v_item ? 'share_class_label'
        and v_item ? 'fiscal_year_end_date'
        and v_item ? 'total_distributions_per_share_unscaled'
        and v_item ? 'total_distributions_per_share_scale'
        and v_item ? 'net_asset_value_end_of_period_unscaled'
        and v_item ? 'net_asset_value_end_of_period_scale'
        and v_item ? 'source_document_url'
      )
    then
      raise exception using
        errcode = '22023',
        message = 'ETF distribution value record has invalid fields';
    end if;
  end loop;

  -- Stable contract-specific key: etf_distribution_values.upsert.v1.
  perform pg_catalog.pg_advisory_xact_lock(3104857211936402577);

  insert into public.etf_distribution_values (
    ticker,
    registrant_cik,
    accession_number,
    fund_name,
    share_class_label,
    fiscal_year_end_date,
    total_distributions_per_share_unscaled,
    total_distributions_per_share_scale,
    net_asset_value_end_of_period_unscaled,
    net_asset_value_end_of_period_scale,
    source_document_url
  )
  select
    populated.ticker,
    populated.registrant_cik,
    populated.accession_number,
    populated.fund_name,
    populated.share_class_label,
    populated.fiscal_year_end_date,
    populated.total_distributions_per_share_unscaled,
    populated.total_distributions_per_share_scale,
    populated.net_asset_value_end_of_period_unscaled,
    populated.net_asset_value_end_of_period_scale,
    populated.source_document_url
  from pg_catalog.jsonb_populate_recordset(
    null::public.etf_distribution_values,
    records
  ) as populated
  on conflict (ticker, fiscal_year_end_date)
  do update set
    registrant_cik = excluded.registrant_cik,
    accession_number = excluded.accession_number,
    fund_name = excluded.fund_name,
    share_class_label = excluded.share_class_label,
    total_distributions_per_share_unscaled =
      excluded.total_distributions_per_share_unscaled,
    total_distributions_per_share_scale =
      excluded.total_distributions_per_share_scale,
    net_asset_value_end_of_period_unscaled =
      excluded.net_asset_value_end_of_period_unscaled,
    net_asset_value_end_of_period_scale =
      excluded.net_asset_value_end_of_period_scale,
    source_document_url = excluded.source_document_url;

  get diagnostics v_upserted_count = row_count;

  return pg_catalog.jsonb_build_object(
    'attempted', v_record_count,
    'upserted', v_upserted_count
  );
end;
$$;

comment on function public.upsert_etf_distribution_values_v1(jsonb) is
'Atomically upserts global ETF annual distribution batches (SEC N-CSR Financial Highlights) for server-side callers, keyed by ticker + fiscal_year_end_date.';

revoke all on function public.upsert_etf_distribution_values_v1(jsonb) from public;
revoke all on function public.upsert_etf_distribution_values_v1(jsonb) from anon;
revoke all on function public.upsert_etf_distribution_values_v1(jsonb) from authenticated;
grant execute on function public.upsert_etf_distribution_values_v1(jsonb) to service_role;

revoke insert, update, delete, truncate
on table public.etf_distribution_values
from service_role;
