-- Sprint 16, Fase 2 (DEC-075): taxa de referencia de mercado, global, mesmo
-- padrao de market_exchange_rates (DEC-052) - sem dono individual, sem RPC
-- de escrita para authenticated, so service_role via RPC dedicada.
--
-- Primeira serie: NTN-B (Tesouro IPCA+ com Juros Semestrais), fonte Tesouro
-- Transparente. Ancora o spread de DY sobre juro real
-- (docs/reference/FII_SEGMENTOS_E_METRICAS.md, secao 3.2/7.2). `series`
-- deixa espaco pra outras taxas de referencia (ex.: TIPS 10 anos via FRED,
-- Fase 4) sem tabela nova.

create table public.market_reference_rates (
  id bigint generated by default as identity primary key,
  series text not null,
  maturity_date date not null,
  rate_scaled bigint not null,
  rate_scale integer not null default 1000000,
  priced_at date not null,
  source text not null,
  created_at timestamptz not null default now(),

  constraint market_reference_rates_series_check check (
    series in ('ntnb-longa')
  ),
  constraint market_reference_rates_source_check check (
    source in ('tesouro-transparente')
  ),
  constraint market_reference_rates_rate_scale_check check (
    rate_scale = 1000000
  ),
  constraint market_reference_rates_identity_unique unique (
    series, source, priced_at
  )
);

create index market_reference_rates_series_priced_at_idx
on public.market_reference_rates (series, priced_at desc);

alter table public.market_reference_rates enable row level security;

create policy "Authenticated users can read global market reference rates"
on public.market_reference_rates
for select
to authenticated
using (true);

revoke all on table public.market_reference_rates from anon;
revoke all on table public.market_reference_rates from authenticated;
grant select on table public.market_reference_rates to authenticated;
grant select, insert, update, delete
on table public.market_reference_rates
to service_role;

revoke all on sequence public.market_reference_rates_id_seq from anon;
revoke all on sequence public.market_reference_rates_id_seq from authenticated;
grant usage, select
on sequence public.market_reference_rates_id_seq
to service_role;

create function public.upsert_market_reference_rates_v1(records jsonb)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_record_count integer;
  v_item jsonb;
  v_key_count integer;
  v_upserted_count integer;
begin
  if records is null or pg_catalog.jsonb_typeof(records) <> 'array' then
    raise exception using
      errcode = '22023',
      message = 'market reference rates batch must be an array';
  end if;

  v_record_count := pg_catalog.jsonb_array_length(records);
  if v_record_count > 20 then
    raise exception using
      errcode = '22023',
      message = 'market reference rates batch exceeds 20 records';
  end if;

  if v_record_count = 0 then
    return pg_catalog.jsonb_build_object('attempted', 0, 'upserted', 0);
  end if;

  for v_item in
    select value
    from pg_catalog.jsonb_array_elements(records)
  loop
    if pg_catalog.jsonb_typeof(v_item) <> 'object' then
      raise exception using
        errcode = '22023',
        message = 'market reference rate record must be an object';
    end if;

    if v_item ? 'id' or v_item ? 'created_at' then
      raise exception using
        errcode = '22023',
        message = 'market reference rate record must not set id or created_at';
    end if;

    select pg_catalog.count(*)
    into v_key_count
    from pg_catalog.jsonb_object_keys(v_item);

    if v_key_count <> 6
      or not (
        v_item ? 'series'
        and v_item ? 'maturity_date'
        and v_item ? 'rate_scaled'
        and v_item ? 'rate_scale'
        and v_item ? 'priced_at'
        and v_item ? 'source'
      )
    then
      raise exception using
        errcode = '22023',
        message = 'market reference rate record has invalid fields';
    end if;
  end loop;

  -- Stable contract-specific key: market_reference_rates.upsert.v1.
  perform pg_catalog.pg_advisory_xact_lock(4826317092550671823);

  insert into public.market_reference_rates (
    series,
    maturity_date,
    rate_scaled,
    rate_scale,
    priced_at,
    source
  )
  select
    populated.series,
    populated.maturity_date,
    populated.rate_scaled,
    populated.rate_scale,
    populated.priced_at,
    populated.source
  from pg_catalog.jsonb_populate_recordset(
    null::public.market_reference_rates,
    records
  ) as populated
  on conflict (series, source, priced_at)
  do update set
    maturity_date = excluded.maturity_date,
    rate_scaled = excluded.rate_scaled,
    rate_scale = excluded.rate_scale;

  get diagnostics v_upserted_count = row_count;

  return pg_catalog.jsonb_build_object(
    'attempted', v_record_count,
    'upserted', v_upserted_count
  );
end;
$$;

comment on function public.upsert_market_reference_rates_v1(jsonb) is
'Atomically upserts global market reference rate batches for server-side callers, keyed by series + source + priced_at.';

revoke all on function public.upsert_market_reference_rates_v1(jsonb) from public;
revoke all on function public.upsert_market_reference_rates_v1(jsonb) from anon;
revoke all on function public.upsert_market_reference_rates_v1(jsonb) from authenticated;
grant execute on function public.upsert_market_reference_rates_v1(jsonb) to service_role;

revoke insert, update, delete, truncate
on table public.market_reference_rates
from service_role;
