-- Sprint 16 pós-encerramento: fechamento histórico B3 por exercício, pra
-- viabilizar o sinal de P/L vs própria série histórica das 5 ações
-- brasileiras do universo fechado (docs/reference/REGRAS_DE_PONTUACAO_RASCUNHO.md,
-- seção 3; DEC-104).
--
-- Fonte: arquivo anual COTAHIST_A<ano>.ZIP da B3 (público, layout de
-- largura fixa), mesmo formato já parseado por
-- supabase/functions/refresh-market-data/b3CotahistParser.ts (usado hoje
-- só pra cotação atual). Viabilidade confirmada com dado real (DEC-096):
-- BBAS3 fecha 2025-12-30 (último pregão do ano) a R$ 21,92 no arquivo de
-- 2025.
--
-- Chave é (ticker, fiscal_year_end_date): fiscal_year_end_date é a mesma
-- referenceDate do exercício anual em fundamental_snapshots (sempre
-- 31/12 pra este universo), não necessariamente um pregão (feriado,
-- fim de semana). trading_date é o pregão real usado - o último pregão
-- em ou antes de fiscal_year_end_date dentro do mesmo ano-calendário do
-- arquivo COTAHIST consultado.
--
-- Mesmo padrão de acesso de etf_distribution_values (DEC-103) e
-- market_etf_valuations/fii_monthly_dividend_yield: tabela global, sem
-- dono individual, RLS com leitura para `authenticated` e escrita só por
-- `service_role` via RPC dedicada.
create table public.stock_historical_close_prices (
  id bigint generated by default as identity primary key,
  ticker text not null,
  fiscal_year_end_date date not null,
  trading_date date not null,
  close_price_in_minor_units bigint not null,
  source text not null default 'b3-cotahist',
  source_archive text not null,
  extracted_at timestamptz not null default now(),

  constraint stock_historical_close_prices_ticker_check check (
    ticker in ('BBAS3', 'ITSA4', 'TAEE11', 'WEGE3', 'PSSA3')
  ),
  constraint stock_historical_close_prices_identity_unique unique (
    ticker, fiscal_year_end_date
  ),
  constraint stock_historical_close_prices_price_check check (
    close_price_in_minor_units > 0
  ),
  constraint stock_historical_close_prices_trading_date_check check (
    trading_date <= fiscal_year_end_date
  ),
  constraint stock_historical_close_prices_source_check check (
    source = 'b3-cotahist'
  )
);

create index stock_historical_close_prices_ticker_fiscal_year_idx
on public.stock_historical_close_prices (ticker, fiscal_year_end_date desc);

alter table public.stock_historical_close_prices enable row level security;

create policy "Authenticated users can read global stock historical close prices"
on public.stock_historical_close_prices
for select
to authenticated
using (true);

revoke all on table public.stock_historical_close_prices from anon;
revoke all on table public.stock_historical_close_prices from authenticated;
grant select on table public.stock_historical_close_prices to authenticated;
grant select, insert, update, delete
on table public.stock_historical_close_prices
to service_role;

revoke all on sequence public.stock_historical_close_prices_id_seq from anon;
revoke all on sequence public.stock_historical_close_prices_id_seq from authenticated;
grant usage, select
on sequence public.stock_historical_close_prices_id_seq
to service_role;

create function public.upsert_stock_historical_close_prices_v1(records jsonb)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_record_count integer;
  v_item jsonb;
  v_key_count integer;
  v_upserted_count integer;
begin
  if records is null or pg_catalog.jsonb_typeof(records) <> 'array' then
    raise exception using
      errcode = '22023',
      message = 'Stock historical close price batch must be an array';
  end if;

  v_record_count := pg_catalog.jsonb_array_length(records);
  if v_record_count > 20 then
    raise exception using
      errcode = '22023',
      message = 'Stock historical close price batch exceeds 20 records';
  end if;

  if v_record_count = 0 then
    return pg_catalog.jsonb_build_object('attempted', 0, 'upserted', 0);
  end if;

  for v_item in
    select value
    from pg_catalog.jsonb_array_elements(records)
  loop
    if pg_catalog.jsonb_typeof(v_item) <> 'object' then
      raise exception using
        errcode = '22023',
        message = 'Stock historical close price record must be an object';
    end if;

    if v_item ? 'id' or v_item ? 'extracted_at' then
      raise exception using
        errcode = '22023',
        message = 'Stock historical close price record must not set id or extracted_at';
    end if;

    select pg_catalog.count(*)
    into v_key_count
    from pg_catalog.jsonb_object_keys(v_item);

    if v_key_count <> 5
      or not (
        v_item ? 'ticker'
        and v_item ? 'fiscal_year_end_date'
        and v_item ? 'trading_date'
        and v_item ? 'close_price_in_minor_units'
        and v_item ? 'source_archive'
      )
    then
      raise exception using
        errcode = '22023',
        message = 'Stock historical close price record has invalid fields';
    end if;
  end loop;

  -- Stable contract-specific key: stock_historical_close_prices.upsert.v1.
  perform pg_catalog.pg_advisory_xact_lock(5108321744019663421);

  insert into public.stock_historical_close_prices (
    ticker,
    fiscal_year_end_date,
    trading_date,
    close_price_in_minor_units,
    source_archive
  )
  select
    populated.ticker,
    populated.fiscal_year_end_date,
    populated.trading_date,
    populated.close_price_in_minor_units,
    populated.source_archive
  from pg_catalog.jsonb_populate_recordset(
    null::public.stock_historical_close_prices,
    records
  ) as populated
  on conflict (ticker, fiscal_year_end_date)
  do update set
    trading_date = excluded.trading_date,
    close_price_in_minor_units = excluded.close_price_in_minor_units,
    source_archive = excluded.source_archive;

  get diagnostics v_upserted_count = row_count;

  return pg_catalog.jsonb_build_object(
    'attempted', v_record_count,
    'upserted', v_upserted_count
  );
end;
$$;

comment on function public.upsert_stock_historical_close_prices_v1(jsonb) is
'Atomically upserts global B3 COTAHIST annual close price batches for server-side callers, keyed by ticker + fiscal_year_end_date.';

revoke all on function public.upsert_stock_historical_close_prices_v1(jsonb) from public;
revoke all on function public.upsert_stock_historical_close_prices_v1(jsonb) from anon;
revoke all on function public.upsert_stock_historical_close_prices_v1(jsonb) from authenticated;
grant execute on function public.upsert_stock_historical_close_prices_v1(jsonb) to service_role;

revoke insert, update, delete, truncate
on table public.stock_historical_close_prices
from service_role;
